# Generated by Django 4.0.3 on 2022-03-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
